name = mobs_andes
description = Adds animals from the Andes region (South America) to your world. Currently includes the alpaca.
depends = mobs
optional_depends = default, ethereal
min_minetest_version = 5.8
title = Mobs Andes
author = ronrob-lu
version = 0.1
